---
kind: pipeline
type: docker
name: default

steps:
- name: publish  
  image: plugins/docker
  settings:
    registry:
      from_secret: DOCKER_REGISTRY
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo:
      from_secret: DOCKER_REPO
    dockerfile: ./Dockerfile
    tags:
      - latest
      - test-drone

trigger:
  event:
    - tag